apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: ecommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
        - name: ml-service
          image: your-ecr-repo/ai-ecommerce-ml-service:latest
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: ml-service-config
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 60
