apiVersion: v1
kind: Service
metadata:
  name: ml-service
  namespace: ecommerce
spec:
  selector:
    app: ml-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: LoadBalancer
