version: "3.8"

services:
  ml-service:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.prod
    image: ai-ecommerce-ml-service:latest
    container_name: ml-service
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=production
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=${REDIS_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
